### ISSUE TITLE
Set Battery Profile

### ISSUE THREAD

**Issue by eppa702** [Racailloux/home-assistant-pijuice#11]
I got PiJuice and the sensors up and running but how can I set the battery profile or other settings for that matter? (don't know if I need to but it seems to be recommended in the official docs). As of now I am using the 12,000mah battery with everything factory default. 

https://github.com/PiSupply/PiJuice/blob/master/Software/Configs/Batteries/LIPO_12000_PIS-1129.JSON

**Comment by Racailloux** [comment]
Hello,
To get the battery setup and all other settings of PiJuice, that needs to be written to the PiJuice memory.
The Home Assistant pijuice integration was only designed to read pijuice informations.

That's the topic for futur updates, but not yet implemented. Like [this one](https://github.com/Racailloux/home-assistant-pijuice/issues/7).
