### ISSUE TITLE
cannot import name 'SensorEntity' from 'homeassistant.components.sensor' 

### ISSUE THREAD

**Issue by V4l3n10** [Racailloux/home-assistant-pijuice#12]
Hi,

First, thanks for putting this together! 

I manually added the files as per your instructions. And when validating configurations prompted the following error:

Platform error sensor.pijuice - cannot import name 'SensorEntity' from 'homeassistant.components.sensor' (/usr/src/homeassistant/homeassistant/components/sensor/__init__.py)

![5049965E-5992-40E4-BA1B-915AF43AB0B9](https://user-images.githubusercontent.com/79058457/153424620-7664ffa8-3bb0-4b1c-ad80-8ff7b7b835db.png)
![E57B6479-D40E-42CF-9ACE-C24EF588C350](https://user-images.githubusercontent.com/79058457/153424623-4b2d64ea-4b33-4e93-9997-62b5d7bc8cea.png)

What am I doing wrong? Please advise 

Thanks 
Val

**Comment by Racailloux** [comment]
Hello,
I am a bit surprised, but perhaps updates could break something.
Can you share the file import structure you have and your configuration.yaml where you imported the integration?
