### ISSUE TITLE
Seeking documentation to explain the sensors

### ISSUE THREAD

**Issue by IanAdd** [Racailloux/home-assistant-pijuice#13]
I have successfully enabled I2C on a standard HA installation and used HACS to install your code.
I have all the sensors reporting values but I do not understand what the values are telling me.
Is there something written up about them?

![pijuice](https://user-images.githubusercontent.com/10492213/191643171-7ad8a0d9-6707-446a-be32-86ba9c65c461.png)

**Comment by Racailloux** [comment]
The sensors don't get any "documentation" because it feels quite understandable. Apparently not so much.

The battery status is the current powering statement (in your screenshot, the power supply is present and the battery is charging.
All sensors about IO, reports about the power supply (voltage, current, status (connected or not) )
The battery sensors are the status if the battery itself (voltage, current)

Let me know if there is any element that is not clear enough.

**Comment by IanAdd** [comment]
Thanks for responding. Perhaps if I draft a document you might correct me and fill in the missing bits. For states I am referring to the image I posted and to the currently reported states I see on my system. I suspect some of my questions would be best answered by PiJuice themselves.

**PiJuice Battery Status**
States:
* normal - ???
* charging from 5v io - The PiJuice Battery is not fully charged and is being topped up via the GPIO bus.
* ?? other states ?

**PiJuice Power Input status**
States:
* Weak - ???
* Not present - ???
* ?? other states ?

**PiJuice Power input IO status**
States:
* Present - connected to a power source ??
* Bad - ??
* ?? other states ?*

**PiJuice Charge**
State:
* example 91% - how full the PiJuice Battery is

**PiJuice Temperature**
State:
* example 24c - ? Battery / Board Temperature ? What temp should be of concern?
* example 9c - how can this temp be correct when the ambience temp is over 20c ?

**PiJuice Battery Voltage**
State:
* example 4.158V - ?? what value range is normal and what should be of concern ?

**PiJuice Battery current**
State:
* example 0.0 A - the current entering/charging the PiJuice from its own micro USB power source ??

**PiJuice IO voltage**
State:
* example 5.18v - the voltage the the PiJuice is delivering to the Raspberry Pi
NB This value should be in the range ?? to ??

**PiJuice IO current**
State:
* example 0.284 A - the current being drawn from the PiJuice by the Raspberry Pi
NB if this value is negative then the PiJuice is being charged from the Raspberry Pi GPIO bus, PiJuice Battery Status will be 'charging from 5v io'
