### ISSUE TITLE
Two sensors missing after HA update to 2023.5.0

### ISSUE THREAD

**Issue by mhwsmits** [Racailloux/home-assistant-pijuice#17]
After update to Home Assistant 2023.5.0 the sensors pijuice_battery_status and pijuice_power_input_io_status are no longer available. The other PiJuice entities are still available. Not using HACS, manual install through configuration.yaml.

**Comment by Racailloux** [comment]
Fixed with commit https://github.com/Racailloux/home-assistant-pijuice/commit/7ae4eecd135924b94d66a8348a96dee8ee384187
