### ISSUE TITLE
No longer working as of 2024.4.1

### ISSUE THREAD

**Issue by ShonP40** [Racailloux/home-assistant-pijuice#26]
After upgrading to HA 2024.4.1 all PiJuice entities stopped working

<img width="372" alt="image" src="https://github.com/Racailloux/home-assistant-pijuice/assets/13995143/26c6a4f7-d135-4873-be93-53ff4c65f682">

Nothing has popped up in the logs about this though

**Comment by HonBl** [comment]
And do you know which version of HA was ok for this integration? I installed integration into 2024.5.5 and there are no sensors appeared, no error log.

**Comment by ShonP40** [comment]
It was working prior to that version

I ended up switching to a different integration though, seems to be better so far + configurable through the UI

https://github.com/modrisb/pijups

So I guess that I’ll just close this issue due to loss of interest
