### ISSUE TITLE
PiJuice IO current to high ?

### ISSUE THREAD

**Issue by domowarrior** [Racailloux/home-assistant-pijuice#4]
Setup : Rpi 3b 
Power connected to Pijuice direct.
battery : 12000 mAh
power supply 2.5 A
latest  version of your excellent Hacs plugin

I choose the right battery config , ( with booting into normal pi OS

All works  correct except PiJuice IO current is way to high,   when charging is between 9 A  and 206 A
when running on Batterij juice alone it is between 12 A and 250 A.
I there another setting in the  Pjuice config i should change ( i left everything on default value except the battery type ( setting for 12000 mAh.
Or is there a error in your code that puts the "." wrong ?

**Comment by Racailloux** [comment]
This display issue should be fixed by v1.1.1.
Please check out and confirm me.

**Comment by domowarrior** [comment]
Hi Racailloux,

I updated to 1.1.1 and now values are normal , both  when charging and running from battery.
Thanks for the fast update, you can close this issue.
Love this plugin  thanks again for developing it, if i can do other testing for you , just let me know.

Regards 

Karel
