### ISSUE TITLE
Event management

### ISSUE THREAD

**Issue by Racailloux** [Racailloux/home-assistant-pijuice#9]
[Event triggering](https://developers.home-assistant.io/docs/device_automation_trigger/)
- Low charge
- Low battery voltage
- No power
- Power present
- etc

**Comment by lcnittl** [comment]
I am - seemingly understanding more of the topic now - not sure if [my proposal in this case](https://community.home-assistant.io/t/pijuice-battery-hat-for-mobile-pi/51151/6?u=lcnittl) really makes sense. Seems that events are only of real use for stateless changes (like a button being pressed, where there is no change of state) and, as soon as states are supplied to HA indeed updates of them are most easily detected with an automation.

Unless, of course, there are events that do not have a state change behind them (have to think about it)
